Repository nebius/soperator, pull requests merged in 2024-12, with the labels that each got.

#211 Release soperator 1.15.5
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  images/worker/slurmd_entrypoint.sh
  internal/consts/version.go
  internal/render/worker/container.go
  internal/render/worker/container_test.go
Labels: release

#215 MSP-3191: add webhook protect delete secret mariadb
  Makefile
  PROJECT
  api/v1/slurmcluster_types.go
  cmd/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/network-policy/allow-webhook-traffic.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/templates/selfsigned-issuer.yaml
  helm/soperator/templates/serving-cert.yaml
  helm/soperator/templates/validate-secrets.yaml
  helm/soperator/templates/webhook-service.yaml
  helm/soperator/values.yaml
  internal/consts/annotation.go
  internal/consts/label.go
  internal/controller/clustercontroller/accounting.go
  internal/render/accounting/mariadb.go
  internal/render/accounting/mariadb_password.go
  internal/webhook/v1/secret_webhook.go
  internal/webhook/v1/secret_webhook_test.go
  test/e2e/e2e_test.go
Labels: feature

#223 MSP-3642: add some configmap values
  Makefile
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/common/configmap.go
  internal/values/slurm_cluster.go
Labels: feature

#228 Set compute instance name as slurm InstanceId
  images/worker/slurmd_entrypoint.sh
  internal/render/worker/container.go
  internal/render/worker/statefulset_test.go
Labels: feature

#231 MSP-3272: Support GDRCopy + preinstall more tools
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  images/common/scripts/install_awscli.sh
  images/common/scripts/install_gdrcopy.sh
  images/common/scripts/install_rclone.sh
  images/jail/init-users/sudoers
  images/jail/jail.dockerfile
  internal/consts/nvidia.go
  internal/render/worker/container.go
  internal/render/worker/container_test.go
  internal/render/worker/statefulset.go
  internal/values/slurm_worker.go
Labels: feature

#249 run enroot containers without root privileges
  images/common/scripts/install_enroot.sh
  images/jail/enroot/enroot.conf
  images/jail/jail.dockerfile
  images/worker/slurmd.dockerfile
  internal/consts/container.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/k8s_daemonset.go
  internal/controller/reconciler/reconciler.go
  internal/render/worker/container.go
  internal/render/worker/daemonset.go
Labels: feature

#265 run build for release
  .github/workflows/one_job.yml
Labels: github_actions

#275 Fix daemonset labels
  internal/consts/component.go
  internal/render/worker/daemonset.go
Labels: fix

#278 Sshd client alive interval 10
  internal/consts/sshd.go
Labels: fix

#281 Soperator release 1.16.1
  VERSION
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  images/jail/gpubench/go.mod
  images/jail/gpubench/go.sum
  images/worker/slurmd.dockerfile
  images/worker/slurmd_entrypoint.sh
  images/worker/sshd_entrypoint.sh
  images/worker/supervisord_entrypoint.sh
  internal/consts/component.go
  internal/consts/sshd.go
  internal/consts/version.go
  internal/render/common/configmap.go
  internal/render/worker/configmap.go
  internal/render/worker/container.go
  internal/render/worker/container_test.go
  internal/render/worker/daemonset.go
  internal/render/worker/statefulset.go
  internal/values/slurm_worker.go
Labels: release

#289 MSP-3849: fix bug soperator does not watch external of configmap
  internal/controller/clustercontroller/reconcile.go
Labels: bug

#290 MSP-3851: remove privilages rights from sleep container sysctl
  internal/render/worker/container.go
Labels: fix

#291 MSP-3652: improve probes accounting, worker and controller
  internal/render/accounting/container.go
  internal/render/controller/container.go
  internal/render/worker/container.go
Labels: fix

#294 delete StartupProbe
  internal/render/accounting/container.go
  internal/render/controller/container.go
  internal/render/worker/container.go
Labels: fix
