Repository nebius/soperator, pull requests merged in 2024-11, with the labels that each got.

#160 add: arrange storage attachment scheduling by storage type
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster-storage/templates/accounting-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/accounting-pv.yaml
  helm/slurm-cluster-storage/templates/controller-spool-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/controller-spool-pv.yaml
  helm/slurm-cluster-storage/templates/jail-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-pv.yaml
  helm/slurm-cluster-storage/templates/jail-submounts-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-submounts-pv.yaml
  helm/slurm-cluster-storage/values.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/values.yaml
  images/worker/slurmd_entrypoint.sh
  internal/consts/version.go
  internal/render/accounting/mariadb.go
  internal/render/accounting/mariadb_test.go
Labels: feature, helm

#176 MSP-2609: fix secret templating and appapormor populatejail
  VERSION
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
  internal/values/slurm_jail.go
  internal/values/slurm_periodic_checks.go
Labels: bug

#178 MSP-3281 add codowners, rm review action
  .github/workflows/auto-assign-review.yml
  .github/workflows/one_job.yml
  CODEOWNERS
Labels: feature

#185 NOTASK: test gpubench
  .github/workflows/gpubench_only.yml
  .github/workflows/one_job.yml
Labels: bug

#187 Sshd keepalive
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/values.yaml
  internal/consts/sshd.go
  internal/consts/version.go
  internal/render/login/configmap.go
Labels: bug

#190 Set UseInfiniband defaul - true
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: other

#191 Release 1.15.3
  .github/workflows/github_release.yml
  .github/workflows/gpubench_only.yml
  .github/workflows/one_job.yml
  Dockerfile
  README.md
  VERSION
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/values.yaml
  images/common/scripts/complement_jail.sh
  images/jail/gpubench/go.mod
  images/jail/gpubench/go.sum
  internal/consts/sshd.go
  internal/consts/version.go
  internal/render/login/configmap.go
Labels: release

#200 Create SECURITY.md
  .github/workflows/one_job.yml
  SECURITY.md
Labels: documentation

#206 Release soperator 1.15.4
  .github/auto_assign.yml
  .github/workflows/one_job.yml
  SECURITY.md
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/_helpers.tpl
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  images/jail/gpubench/go.mod
  images/jail/gpubench/go.sum
  images/worker/slurmd_entrypoint.sh
  internal/check/resources.go
  internal/check/resources_test.go
  internal/consts/version.go
  internal/render/login/configmap.go
  internal/render/worker/container.go
  internal/render/worker/container_test.go
  internal/render/worker/statefulset.go
  internal/render/worker/statefulset_test.go
Labels: release
