Repository nebius/soperator, pull requests merged in 2024-10, with the labels that each got.

#109 feature: create release with changelog
  .github/workflows/github_release.yml
Labels: feature

#108 MSP-3088: Fix configurable ulimits
  VERSION
  images/jail/enroot-conf/enroot.conf
  images/worker/slurmd_entrypoint.sh
  internal/render/common/configmap.go
  internal/render/common/configmap_test.go
Labels: bug

#117 fix: remove fromTag
  .github/workflows/github_release.yml
Labels: fix

#119 Fix versions and add versions check test
  .github/workflows/one_job.yml
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
Labels: fix, test

#118 Accept no IP for LB Service type
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
  internal/render/login/service.go
  internal/values/validate.go
Labels: go, fix

#121 Fixes for version check and yq installation
  .github/workflows/github_release.yml
  .github/workflows/one_job.yml
  Makefile
Labels: fix

#123 create release only for new tags
  .github/workflows/github_release.yml
Labels: fix

#125 FIX: Use empty string as default for `sshdServiceLoadBalancerIP`
  Makefile
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
Labels: fix, helm

#128 ci: find `fromTag` and `toTag` on our own w/o `tag_resolver`
  .github/workflows/github_release.yml
  .github/workflows/one_job.yml
Labels: github_actions, fix, ignore-for-release

#131 feature: slurm partition configuration
  VERSION
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
  internal/render/common/configmap.go
  internal/values/slurm_cluster.go
  internal/values/slurm_config.go
  internal/values/validate.go
Labels: feature

#132 feature: Enable Scrontab
  internal/render/common/configmap.go
Labels: feature

#133 CPU-only workers w/o toolkit-validation
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  images/worker/slurmd_entrypoint.sh
  internal/consts/version.go
  internal/render/worker/statefulset.go
  internal/render/worker/statefulset_test.go
Labels: go, fix

#134 MSP-3091: fix reconcile condition accounting
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/mariadb.go
Labels: go, fix

#135 Release v1.14.11
  VERSION
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  images/worker/slurmd_entrypoint.sh
  internal/consts/version.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/mariadb.go
  internal/render/common/configmap.go
  internal/render/worker/statefulset.go
  internal/render/worker/statefulset_test.go
  internal/values/slurm_cluster.go
  internal/values/slurm_config.go
  internal/values/validate.go
Labels: release

#145 Fix getting uniq node for all slurm partitions in nccl test
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  images/nccl_benchmark/scripts/srun_perf.sh
  internal/consts/version.go
Labels: bug

#146 Release 1.14.13
  .github/workflows/one_job.yml
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  images/nccl_benchmark/scripts/srun_perf.sh
  internal/consts/version.go
Labels: release

#148 option to configure annotation for login svc
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
Labels: feature, helm

#150 Release 1.14.14
  .github/workflows/one_job.yml
  Makefile
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
Labels: release

#151 perf(images): use multi-stage to reduce populate_jail image size
  images/populate_jail/populate_jail.dockerfile
Labels: bug, images

#154 Helm (`slurm-cluster-storage`): Configure scheduling for particular storage targets
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster-storage/templates/accounting-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/accounting-pv.yaml
  helm/slurm-cluster-storage/templates/controller-spool-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/controller-spool-pv.yaml
  helm/slurm-cluster-storage/templates/jail-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-pv.yaml
  helm/slurm-cluster-storage/templates/jail-submounts-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-submounts-pv.yaml
  helm/slurm-cluster-storage/values.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
Labels: feature, helm
