Repository nebius/soperator, pull requests merged in 2025-09, with the labels that each got.

#1522 [nccl-debug] Don't try chmodding files and directories without a need
  images/common/spank-nccl-debug/Makefile
  images/common/spank-nccl-debug/README.md
  images/common/spank-nccl-debug/src/snccld.c
  images/common/spank-nccl-debug/src/snccld_state.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.h
  images/common/spank-nccl-debug/src/snccld_util_oplock.c
Labels: enhancement, images, observability

#1526 Bump health checker 1.0.0-150
  helm/soperator-activechecks/values.yaml
  images/jail/jail.dockerfile
Labels: feature

#1534 Support passing extraArgs for node-exporter
  helm/soperator-fluxcd/templates/vm-stack.yaml
  helm/soperator-fluxcd/values.yaml
Labels: helm

#1538 Add reason label to slurm_node_info metric for better observability
  docs/slurm-exporter.md
  internal/exporter/collector.go
  internal/exporter/collector_test.go
Labels: observability

#1546 configurable worker resoucres in e2e
  .github/workflows/e2e_test.yml
  test/e2e/e2e_test.go
Labels: ignore-for-release

#1550 sleep before getting new token in e2e
  .github/workflows/e2e_test.yml
Labels: ignore-for-release

#1541 [nccld-plugin] Make user responsible for correct rights of the output directory
  helm/soperator-activechecks/scripts/ensure-dir-snccld-logs.sh
  helm/soperator-activechecks/templates/ensure-dir-snccld-logs.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-fluxcd/templates/slurm-cluster-storage.yaml
  helm/soperator-fluxcd/templates/slurm-cluster.yaml
  helm/soperator-fluxcd/templates/soperator-activechecks.yaml
  helm/soperator-fluxcd/templates/soperatorchecks.yaml
  images/common/spank-nccl-debug/src/snccld.c
  images/common/spank-nccl-debug/src/snccld_log.h
  images/common/spank-nccl-debug/src/snccld_state.c
  images/common/spank-nccl-debug/src/snccld_state.h
  images/common/spank-nccl-debug/src/snccld_util_dir_file.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.h
Labels: enhancement, fix, helm, images, observability

#1556 remove complement_jail.sh from checks
  helm/soperator-activechecks/scripts/run-extensive-check-on-reservations.sh
  images/slurm_check_job/slurm_check_job.dockerfile
  images/slurm_check_job/slurm_check_job_entrypoint.sh
Labels: ignore-for-release

#1557 Fill out status for Active Checks
  api/v1alpha1/activecheck_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  helm/soperator-activechecks/templates/wait-for-checks-job.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/consts/conditions.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
Labels: fix

#1574 remove appormore deny for libEGL_ for running docker active check image
  internal/render/common/apparmorprofile.go
Labels: feature

#1573 bump nc-health-checker_1.0.0-151.250904
  helm/soperator-activechecks/values.yaml
  images/jail/jail.dockerfile
Labels: feature

#1569 NFS Server helm chart fixes
  helm/nfs-server/README.md
  helm/nfs-server/templates/pvc.yaml
  helm/nfs-server/templates/service.yaml
  helm/nfs-server/templates/statefulset.yaml
  helm/nfs-server/values.yaml
Labels: helm

#1583 DCGM Exporter fix for toolkit validation
  helm/soperator-dcgm-exporter/templates/daemonset.yaml
  helm/soperator-dcgm-exporter/values.yaml
  helm/soperator-fluxcd/templates/dcgm-exporter.yaml
  helm/soperator-fluxcd/values.yaml
Labels: fix, helm

#1572 Add wait after users creation + Split all-reduce-perf + Fix dcgmi_diag_r1
  helm/slurm-cluster/slurm_scripts/gpu_health_check.py
  helm/soperator-activechecks/scripts/all-reduce-perf-nccl-with-ib.sh
  helm/soperator-activechecks/scripts/all-reduce-perf-nccl-without-ib.sh
  helm/soperator-activechecks/scripts/create-user-soperatorchecks.sh
  helm/soperator-activechecks/scripts/create-user.sh
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-with-ib.yaml
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-without-ib.yaml
Labels: fix

#1585 remove-hc-host-service-check
  helm/slurm-cluster/slurm_scripts/hc_host_service.sh
  helm/slurm-cluster/slurm_scripts/hc_program.sh
  helm/slurm-cluster/slurm_scripts/prolog.sh
  helm/slurm-cluster/templates/slurm-scripts-cm.yaml
Labels: fix

#1592 Update health-checker version to 1.0.0-156.250917 in 1.21
  images/jail/jail.dockerfile
Labels: ignore-for-release

#1582 Fix passive check filtering
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/slurm_scripts/check_runner.py
  helm/slurm-cluster/slurm_scripts/checks.json
  helm/slurm-cluster/slurm_scripts/cleanup_enroot.sh
  helm/soperator-activechecks/scripts/all-reduce-perf-nccl-with-ib.sh
  helm/soperator-activechecks/scripts/all-reduce-perf-nccl-without-ib.sh
  helm/soperator-activechecks/scripts/cuda-samples.sh
  helm/soperator-activechecks/scripts/dcgmi-diag-r2.sh
  helm/soperator-activechecks/scripts/dcgmi-diag-r3.sh
  helm/soperator-activechecks/scripts/enroot-cleanup.sh
  helm/soperator-activechecks/scripts/extensive-check.sh
  helm/soperator-activechecks/scripts/gpu-fryer.sh
  helm/soperator-activechecks/scripts/ib-perf.sh
  helm/soperator-activechecks/scripts/mem-perf.sh
  helm/soperator-activechecks/scripts/prepull-container-image.sh
  helm/soperator-activechecks/scripts/soperator-outputs-logs-cleaner.sh
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-with-ib.yaml
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-without-ib.yaml
  helm/soperator-activechecks/templates/cuda-samples.yaml
  helm/soperator-activechecks/templates/dcgmi-diag-r2.yaml
  helm/soperator-activechecks/templates/enroot-cleanup.yaml
  helm/soperator-activechecks/templates/ensure-dir-snccld-logs.yaml
  helm/soperator-activechecks/templates/gpu-fryer.yaml
  helm/soperator-activechecks/templates/ib-perf.yaml
  helm/soperator-activechecks/templates/mem-perf.yaml
  helm/soperator-activechecks/templates/soperator-outputs-logs-cleaner.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  images/jail/motd/20-slurm-stats
  images/slurm_check_job/slurm_check_job_entrypoint.sh
Labels: feature, fix

#1587 Slurm 25.05.3
  Makefile
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/values.yaml
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/bind_slurm_common.sh
  images/common/spank-nccl-debug/Makefile
  images/common/spank-nccl-debug/docker/base.dockerfile
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/restd/slurmrestd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#1599 Extract Enroot's config paths to config dir
  images/common/enroot/custom-dirs.conf
  images/common/enroot/enroot.conf
  images/common/scripts/install_enroot.sh
  images/login/sshd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: enhancement, fix, images

#1602 change k8up-cleanup image
  helm/soperator-fluxcd/templates/backup.yaml
  helm/soperator-fluxcd/values.yaml
Labels: fix

#1604 Extract Enroot's config paths to config dir
  images/common/enroot/custom-dirs.conf
  images/common/enroot/enroot.conf
  images/common/scripts/install_enroot.sh
  images/login/sshd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: enhancement, fix, images

#1607 bump soperator version to 1.21.14
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1609 Replace automatic release trigger with manual workflow dispatch
  .github/workflows/github_release.yml
  .github/workflows/one_job.yml
Labels: ignore-for-release

#1562 Configurable values for ActiveChecks chart
  helm/soperator-activechecks/scripts/upgrade-health-checker.sh
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-with-ib.yaml
  helm/soperator-activechecks/templates/all-reduce-perf-nccl-without-ib.yaml
  helm/soperator-activechecks/templates/create-user-soperatorchecks.yaml
  helm/soperator-activechecks/templates/create-user.yaml
  helm/soperator-activechecks/templates/cuda-samples.yaml
  helm/soperator-activechecks/templates/dcgmi-diag-r2.yaml
  helm/soperator-activechecks/templates/dcgmi-diag-r3.yaml
  helm/soperator-activechecks/templates/enroot-cleanup.yaml
  helm/soperator-activechecks/templates/ensure-dir-snccld-logs.yaml
  helm/soperator-activechecks/templates/extensive-check.yaml
  helm/soperator-activechecks/templates/gpu-fryer.yaml
  helm/soperator-activechecks/templates/ib-perf.yaml
  helm/soperator-activechecks/templates/install-package.yaml
  helm/soperator-activechecks/templates/mem-perf.yaml
  helm/soperator-activechecks/templates/prepull-container-image.yaml
  helm/soperator-activechecks/templates/soperator-outputs-logs-cleaner.yaml
  helm/soperator-activechecks/templates/ssh-check.yaml
  helm/soperator-activechecks/templates/upgrade-cuda.yaml
  helm/soperator-activechecks/templates/upgrade-health-checker.yaml
  helm/soperator-activechecks/templates/wait-for-topology.yaml
  helm/soperator-activechecks/values.yaml
  test/e2e/e2e_test.go
Labels: feature

#1611 Add pull request template for improved PR documentation
  .github/ISSUE_TEMPLATE/release.md
  .github/pull_request_template.md
Labels: ignore-for-release

#1615 add delete-not-ready-nodes=true by default in helm
  helm/soperatorchecks/values.yaml
Labels: helm
