Repository nebius/soperator, pull requests merged in 2025-05, with the labels that each got.

#813 #792 [soperatorchecks] Add Sbatchscript field for creating sbatch con…
  api/v1alpha1/activecheck_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  config/rbac/soperatorchecks/role.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperatorchecks/templates/soperator-checks-rbac.yaml
  internal/consts/configmap.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/naming/naming.go
  internal/render/soperatorchecks/configmap.go
  internal/render/soperatorchecks/container.go
  internal/render/soperatorchecks/pod.go
Labels: feature

#840 fix fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator
  fluxcd/environment/nebius-cloud/base/flux_kustomization.yaml
Labels: ignore-for-release

#841 453 controller for slurm clients
  cmd/soperatorchecks/main.go
  config/soperatorchecks/soperatorchecks.yaml
  helm/soperatorchecks/templates/deployment.yaml
  helm/soperatorchecks/values.yaml
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/controller/soperatorchecks/k8s_nodes_controller.go
  internal/controller/soperatorchecks/slurm_api_clients_controller.go
  internal/controller/soperatorchecks/slurm_nodes_controller.go
  internal/controller/soperatorchecks/slurm_nodes_controller_test.go
  internal/slurmapi/client.go
  internal/slurmapi/client_set.go
Labels: fix

#869 Allow running ci in all branches, not only in dev/main
  .github/workflows/one_job.yml
Labels: ignore-for-release

#871 Install deb packages from Nebius deb repo for slurm exporter image with slurm 24.05.7
  images/exporter/exporter.dockerfile
Labels: feature

#879 remove custom init containers mounts validation
  internal/values/validate.go
Labels: ignore-for-release

#880 Install deb packages from Nebius deb repo for jail image with slurm 24.05.7
  images/common/scripts/install_container_toolkit.sh
  images/common/scripts/install_docker_cli.sh
  images/common/scripts/install_openmpi.sh
  images/common/scripts/install_python.sh
  images/jail/jail.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#890 push charts on push to dev/main
  .github/workflows/one_job.yml
Labels: ignore-for-release

#887 Install deb packages from Nebius deb repo for login image with slurm 24.05.7
  images/common/scripts/install_enroot.sh
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#891 Install packages from Nebius deb registry for nccl_benchmark docker image
  images/common/scripts/install_munge.sh
  images/nccl_benchmark/nccl_benchmark.dockerfile
Labels: feature

#893 Change base image for populate_jail image
  images/populate_jail/populate_jail.dockerfile
Labels: feature

#895 Install deb packages from Nebius deb repo for slurm check image with slurm 24.05.7
  images/slurm_check_job/slurm_check_job.dockerfile
Labels: feature

#899 retry allocation deletion
  test/e2e/e2e_test.go
Labels: ignore-for-release

#898 Use Nebius public debian registry for package installation
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/install_awscli.sh
  images/common/scripts/install_chroot_plugin.sh
  images/common/scripts/install_container_toolkit.sh
  images/common/scripts/install_docker_cli.sh
  images/common/scripts/install_enroot.sh
  images/common/scripts/install_munge.sh
  images/common/scripts/install_openmpi.sh
  images/common/scripts/install_parallel.sh
  images/common/scripts/install_python.sh
  images/common/scripts/install_pyxis_plugin.sh
  images/common/scripts/install_rclone.sh
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/k8s_check_job/k8s_check_job.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/restd/slurmrestd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#916 Fix tolerations in exporter
  internal/controller/clustercontroller/common.go
  internal/controller/clustercontroller/exporter.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/render/accounting/pod.go
  internal/render/prometheus/pod.go
  internal/render/rest/pod.go
  internal/render/sconfigcontroller/pod.go
Labels: bug

#925 Using X64 tag for CI runner
  .github/workflows/one_job.yml
Labels: ignore-for-release

#931 add crds k8up
  fluxcd/environment/nebius-cloud/base/kustomization.yaml
Labels: ignore-for-release

#934 hotfix: change helm chart test
  .github/workflows/delete-kind-cluster.yml
  .github/workflows/helm_chart.yml
  helm/soperator/templates/proxy-rbac.yaml
Labels: ignore-for-release

#941 CI version refactoring
  .github/workflows/e2e_test.yml
  .github/workflows/gpubench_only.yml
  .github/workflows/one_job.yml
  .gitignore
  Makefile
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/values.yaml
Labels: ignore-for-release

#943 Move dockerfiles to images.
  .dockerignore
  .github/workflows/one_job.yml
  Makefile
  images/accounting/slurmdbd.dockerfile
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/munge/munge.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/rebooter/rebooter.dockerfile
  images/restd/slurmrestd.dockerfile
  images/sconfigcontroller/sconfigcontroller.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/soperator/Dockerfile
  images/soperatorchecks/soperatorchecks.dockerfile
  images/worker/slurmd.dockerfile
Labels: ignore-for-release

#948 change soperator helm chart fullname
  helm/soperator/templates/_helpers.tpl
  helm/soperator/templates/binding-rbac.yaml
  helm/soperator/templates/deployment.yaml
  helm/soperator/templates/leader-election-rbac.yaml
  helm/soperator/templates/manager-rbac.yaml
  helm/soperator/templates/metrics-reader-rbac.yaml
  helm/soperator/templates/metrics-service.yaml
  helm/soperator/templates/proxy-rbac.yaml
  helm/soperator/templates/selfsigned-issuer.yaml
  helm/soperator/templates/serviceaccount.yaml
  helm/soperator/templates/serving-cert.yaml
  helm/soperator/templates/soperator-checks-rbac.yaml
  helm/soperator/templates/validate-secrets.yaml
  helm/soperator/templates/webhook-service.yaml
Labels: ignore-for-release

#951 hotfix: soperato helm chart
  helm/soperator/templates/deployment.yaml
  helm/soperator/templates/validate-secrets.yaml
Labels: ignore-for-release

#952 add missing go binary into wf
  .github/workflows/helm_chart.yml
Labels: ignore-for-release

#954 Hotfix-helm-action
  .github/workflows/helm_chart.yml
  .github/workflows/one_job.yml
Labels: ignore-for-release

#950 feat: Decouple `ServiceAccountReconciler` from `ActiveCheckReconciler` sync
  api/v1alpha1/activecheck_types.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/consts/activecheck.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/serviceaccount_controller.go
Labels: feature
