Repository nebius/soperator, pull requests merged in 2025-07, with the labels that each got.

#1111 #1060 Move output and error params to sbatch call
  helm/soperator-activechecks/overrides/all_reduce_perf_nccl.yaml
  helm/soperator-activechecks/overrides/clear_enroot.yaml
  images/slurm_check_job/slurm_check_job_entrypoint.sh
  images/slurm_check_job/slurm_submit_array_job.sh
Labels: feature

#1132 hotfix: change customMounts issue with empty array
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
Labels: bug

#1133 Release 1.21.2
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1135 NOTIC: Fix cuda-pins versions
  images/jail/pin_packages/cuda-pins
Labels: fix

#1134 Release 1.21.2
  Makefile
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster-storage/templates/_helpers.tpl
  helm/slurm-cluster-storage/templates/jail-mount-daemonset.yaml
  helm/slurm-cluster-storage/tests/mashedkebab_test.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  images/jail/pin_packages/cuda-pins
  internal/consts/version.go
Labels: release

#1142 notask: set TopologyPlugin to topology/tree by default
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: fix

#1151 Set `out-stdout=1` if user provided `NCCL_DEBUG` on their own
  images/common/spank-nccl-debug/README.md
  images/common/spank-nccl-debug/src/snccld.c
  images/common/spank-nccl-debug/src/snccld_args.h
Labels: enhancement, other

#1163 change registry
  helm/soperator-fluxcd/values.yaml
Labels: ignore-for-release

#1164 Change the granting logic for sconfigcontroller
  config/rbac/clustercontroller/role.yaml
  helm/soperator/templates/manager-rbac.yaml
  internal/controller/clustercontroller/reconcile.go
Labels: fix

#1167 fix boot disk script in configmap
  helm/slurm-cluster/templates/slurm-scripts-cm.yaml
Labels: ignore-for-release

#1176 fix topology
  internal/controller/topologyconfcontroller/workertopology_controller.go
  internal/controller/topologyconfcontroller/workertopology_controller_test.go
Labels: bug

#1179 Release soperator 1.21.6
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
  internal/controller/topologyconfcontroller/topology_graph.go
  internal/controller/topologyconfcontroller/topology_graph_test.go
Labels: release

#1184 Fix REST deployment to respect configured replica count from CRD
  internal/render/rest/container.go
  internal/render/rest/rest.go
Labels: bug

#1191 [fix] vmagent scrape kubelet metrics with large lables per node
  helm/soperator-fluxcd/templates/vm-stack.yaml
Labels: fix

#1197 [fix] watch kruise controller only soperator ns and set default limits
  helm/soperator-fluxcd/templates/kruise.yaml
  helm/soperator-fluxcd/values.yaml
Labels: fix

#1205 [fix] bug with dependency kruise
  helm/soperator-fluxcd/templates/kruise.yaml
  helm/soperator-fluxcd/templates/soperator.yaml
  helm/soperator-fluxcd/values.yaml
Labels: bug

#1211 Fix soperatorchecks homedir in slurm check job image
  images/slurm_check_job/slurm_check_job_entrypoint.sh
  images/slurm_check_job/slurm_submit_array_job.sh
Labels: fix

#1207 #1083 Fix active checks for manual runs
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/render/soperatorchecks/cronjob.go
  internal/render/soperatorchecks/pod.go
Labels: bug

#1212 cleanup backup bucket on destroy
  .github/workflows/e2e_test.yml
  test/e2e/e2e_test.go
Labels: ignore-for-release

#1214 temporary remove install aws in e2e
  .github/workflows/e2e_test.yml
Labels: ignore-for-release

#1209 [fix] fix events to sconfigcontroller and replace get to list
  cmd/sconfigcontroller/main.go
  images/common/scripts/bind_slurm_common.sh
  images/common/scripts/complement_jail.sh
  images/controller/slurmctld_entrypoint.sh
  images/jail/jail.dockerfile
  images/nccl_benchmark/nccl_benchmark_entrypoint.sh
  images/slurm_check_job/slurm_check_job_entrypoint.sh
  images/worker/supervisord_entrypoint.sh
  images/worker/wait-for-controller.sh
  internal/controller/clustercontroller/reconcile.go
  internal/controller/sconfigcontroller/controller.go
  internal/controller/sconfigcontroller/controller_test.go
  internal/controller/topologyconfcontroller/workertopology_controller.go
  internal/render/sconfigcontroller/initcontainer.go
  internal/render/sconfigcontroller/role.go
Labels: bug

#1230 Fix activecheck prolog path
  images/slurm_check_job/slurm_submit_array_job.sh
Labels: fix

#1243 fix rebooter incorrect limit cpu
  internal/render/nodeconfigurator/container.go
Labels: bug

#1244 Fix empty user_name labels in job_info metric
  docs/slurm-exporter.md
  images/restd/slurmrestd_entrypoint.sh
  internal/controller/clustercontroller/rest.go
  internal/exporter/collector.go
  internal/exporter/collector_test.go
  internal/render/common/volume.go
  internal/render/exporter/container.go
  internal/render/exporter/pod.go
  internal/render/exporter/pod_test.go
  internal/render/rest/container.go
  internal/render/rest/pod.go
  internal/render/rest/rest.go
  internal/slurmapi/job.go
  internal/values/slurm_exporter.go
  internal/values/slurm_rest.go
Labels: bug

#1239 Improve sconfigcontroller FileStore.Add: catch close errors and switch files atomically
  internal/controller/sconfigcontroller/file_store.go
Labels: feature

#1245 bump 1.21.9
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1259 [soperator] remove opentlemetry crd. It does not used #1075
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/rbac/clustercontroller/role.yaml
  go.mod
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/templates/manager-rbac.yaml
  internal/check/installed_crd.go
  internal/controller/clustercontroller/benchmark.go
  internal/controller/clustercontroller/common.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/otel.go
  internal/controller/reconciler/otel_test.go
  internal/controller/reconciler/pod_monitor_test.go
  internal/naming/naming.go
  internal/render/accounting/vars_test.go
  internal/render/benchmark/container.go
  internal/render/benchmark/container_test.go
  internal/render/benchmark/cronjob.go
  internal/render/otel/otel.go
  internal/render/otel/otel_test.go
  internal/render/worker/role_binding.go
  internal/render/worker/role_binding_test.go
  internal/values/slurm_cluster.go
Labels: fix

#1160 Upgrade on ubuntu noble
  .gitignore
  Makefile
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/values.yaml
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/install_openmpi.sh
  images/common/scripts/install_python.sh
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/k8s_check_job/k8s_check_job.dockerfile
  images/login/sshd.dockerfile
  images/munge/munge.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/restd/slurmrestd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#1273 Fix Slurm controller failover #1268
  internal/controller/clustercontroller/controller.go
  internal/render/common/configmap.go
  internal/render/controller/container.go
  internal/render/controller/service.go
Labels: fix

#1301 Add time metrics to slurm_job_info metric for comprehensive job monitoring
  docs/slurm-exporter.md
  internal/exporter/collector.go
  internal/exporter/collector_test.go
  internal/slurmapi/job.go
Labels: enhancement

#1291 [soperatorchecks] Unknown status for Ready type of kubelet
  cmd/soperatorchecks/main.go
  internal/consts/conditions.go
  internal/controller/soperatorchecks/k8s_nodes_controller.go
  internal/controller/soperatorchecks/k8s_nodes_controller_test.go
Labels: fix

#1309 add dcgmi diag -r3 bootstrap check
  helm/soperator-activechecks/scripts/dcgmi-diag-r3.sh
  helm/soperator-activechecks/templates/dcgmi-diag-r3.yaml
Labels: feature

#1321 Remove controller service DNS check from worker wait logic to support failover scenarios
  images/worker/wait-for-controller.sh
  internal/controller/clustercontroller/worker.go
  internal/render/worker/container.go
  internal/render/worker/statefulset.go
  internal/render/worker/statefulset_test.go
Labels: bug

#1251 Soperator notifier chart
  Makefile
  helm/soperator-notifier/.helmignore
  helm/soperator-notifier/Chart.yaml
  helm/soperator-notifier/templates/01_secret.yml
  helm/soperator-notifier/templates/02_config.yml
  helm/soperator-notifier/templates/03_manager.yml
  helm/soperator-notifier/templates/04_rule.yml
  helm/soperator-notifier/templates/05_alert.yml
  helm/soperator-notifier/templates/_helpers.00_slack.tpl
  helm/soperator-notifier/templates/_helpers.02_config.tpl
  helm/soperator-notifier/templates/_helpers.03_manager.tpl
  helm/soperator-notifier/templates/_helpers.04_rule.tpl
  helm/soperator-notifier/templates/_helpers.05_alert.tpl
  helm/soperator-notifier/templates/_helpers.tpl
  helm/soperator-notifier/tests/01_secret_test.yaml
  helm/soperator-notifier/tests/02_config_test.yaml
  helm/soperator-notifier/tests/03_manager_test.yaml
  helm/soperator-notifier/tests/04_rule_test.yaml
  helm/soperator-notifier/tests/05_alert_test.yaml
  helm/soperator-notifier/tests/common_metadata_test.yaml
  helm/soperator-notifier/values.yaml
Labels: enhancement, helm

#1334 Build go base image locally
  .github/workflows/one_job.yml
  Makefile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/rebooter/rebooter.dockerfile
  images/sconfigcontroller/sconfigcontroller.dockerfile
  images/soperator-exporter/soperator-exporter.dockerfile
  images/soperator/Dockerfile
  images/soperatorchecks/soperatorchecks.dockerfile
Labels: fix

#1343 Detect stable builds by version tag instead of VERSION file
  .github/workflows/one_job.yml
Labels: ignore-for-release

#1345 [nccl-debug] Use chmod instead of umask
  images/common/spank-nccl-debug/src/snccld.c
  images/common/spank-nccl-debug/src/snccld_state.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.h
  images/common/spank-nccl-debug/src/snccld_util_oplock.c
Labels: bug, enhancement, fix, images

#1349 Bump soperator version to 1.21.10.
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator-notifier/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1347 Bump container toolkit and do not install it into the jail
  images/common/scripts/install_container_toolkit.sh
  images/jail/jail.dockerfile
Labels: feature

#1355 Add workflow to automatically create merge-back PRs from release branches to main
  .github/workflows/auto_merge_back.yml
  .github/workflows/scripts/auto-merge-back.sh
Labels: ignore-for-release
