Repository nebius/soperator, pull requests merged in 2025-01, with the labels that each got.

#287 Separate sshd configs for login and worker nodes
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/consts/configmap.go
  internal/consts/volume.go
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/worker.go
  internal/naming/naming.go
  internal/render/common/configmap.go
  internal/render/common/secret.go
  internal/render/common/volume.go
  internal/render/login/configmap.go
  internal/render/login/container.go
  internal/render/login/secret.go
  internal/render/login/volume.go
  internal/render/worker/configmap.go
  internal/render/worker/container.go
  internal/render/worker/volume.go
  internal/values/slurm_login.go
  internal/values/slurm_worker.go
  internal/values/validate.go
Labels: feature

#295 MSP-3868: delete ownerReferences for mariadb secrets
  internal/controller/clustercontroller/accounting.go
Labels: fix

#296 gpubench add more informations in output
  images/jail/gpubench/main.go
Labels: fix

#297 MSP-3308: delete unused NCCLTypeH100GPUCluster topology
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/crd/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/consts/nccl_topology_type.go
  internal/render/worker/configmap.go
Labels: fix

#301 MSP-3569: delete accounting pod, svc and mariadb when accounting false
  internal/controller/clustercontroller/accounting.go
  internal/controller/clustercontroller/controller.go
  internal/controller/clustercontroller/exporter.go
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/rest.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/deployment.go
  internal/controller/reconciler/deployment_test.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/k8s_role.go
  internal/controller/reconciler/k8s_role_test.go
  internal/controller/reconciler/k8s_rolebinding_test.go
  internal/controller/reconciler/k8s_rolebinging.go
  internal/controller/reconciler/k8s_service.go
  internal/controller/reconciler/mariadb.go
Labels: feature

#309 MSP-3918: Fix bug reconciliation logic for scenarios with maintenance=true and accounting=false
  internal/controller/clustercontroller/accounting.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/reconciler/deployment.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/k8s_role.go
  internal/controller/reconciler/k8s_rolebinging.go
  internal/controller/reconciler/k8s_service.go
  internal/controller/reconciler/mariadb.go
  internal/controller/reconciler/otel.go
  internal/controller/reconciler/pod_monitor.go
  internal/controller/reconciler/pod_monitor_test.go
Labels: bug

#313 add priority class
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/default/manager_auth_proxy_patch.yaml
  helm/slurm-cluster/templates/priority-class.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  internal/render/worker/statefulset.go
  internal/values/slurm_worker.go
Labels: feature

#314 refactor otel
  internal/controller/reconciler/fake_error_client_test.go
  internal/controller/reconciler/otel.go
  internal/controller/reconciler/otel_test.go
Labels: ignore-for-release

#316 Update Slurm to 24.05.5, fix MPI/PMIx bug, update README, and remove AppArmor hack
  Makefile
  README.md
  docs/limitations.md
  helm/slurm-cluster/values.yaml
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/install_openmpi.sh
  images/common/scripts/install_pmix.sh
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/restd/slurmrestd.dockerfile
  images/worker/slurmd.dockerfile
  images/worker/supervisord_entrypoint.sh
  internal/render/common/apparmorprofile.go
  internal/render/common/configmap.go
Labels: bug, documentation, feature

#319 [Fix] Install libpmix into nccl-benchmark image
  images/nccl_benchmark/nccl_benchmark.dockerfile
Labels: fix

#320 Remove openmpi from controller
  images/controller/slurmctld.dockerfile
Labels: fix

#332 Revert "Print actual command before executing it in bash scripts"
  images/accounting/slurmdbd_entrypoint.sh
  images/common/scripts/install_docker.sh
  images/common/scripts/install_docker_cli.sh
  images/controller/slurmctld_entrypoint.sh
  images/jail/scripts/createuser.sh
  images/login/sshd_entrypoint.sh
  images/munge/munge_entrypoint.sh
  images/nccl_benchmark/nccl_benchmark_entrypoint.sh
  images/nccl_benchmark/scripts/srun_perf.sh
  images/restd/slurmrestd_entrypoint.sh
  images/worker/scripts/gpu_healthcheck.sh
  images/worker/slurmd_entrypoint.sh
  images/worker/supervisord_entrypoint.sh
Labels: other

#334 MSP-3992: fix bug with empty version of annotation
  internal/controller/reconciler/k8s_statefulset.go
  internal/controller/reconciler/k8s_statefulset_test.go
Labels: bug

#333 Move gpubench to worker image and bind mount it
  images/jail/jail.dockerfile
  images/worker/slurmd.dockerfile
  images/worker/supervisord_entrypoint.sh
Labels: feature

#339 Move enroot inside images and bind mount it
  .github/workflows/gpubench_only.yml
  images/common/enroot/enroot.conf
  images/common/scripts/complement_jail.sh
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/worker/gpubench/go.mod
  images/worker/gpubench/go.sum
  images/worker/gpubench/main.go
  images/worker/gpubench/main_test.go
  images/worker/slurmd.dockerfile
  images/worker/supervisord_entrypoint.sh
Labels: feature

#354 [FIX] Add patching for service annotations [MSP-3801]
  internal/controller/reconciler/k8s_service.go
Labels: bug, go, fix

#356 fix: update AppArmor profile to allow creation of library links
  internal/render/common/apparmorprofile.go
Labels: fix

#357 NOTASK: add debug logs
  cmd/main.go
  internal/controller/clustercontroller/accounting.go
  internal/controller/clustercontroller/benchmark.go
  internal/controller/clustercontroller/common.go
  internal/controller/clustercontroller/controller.go
  internal/controller/clustercontroller/exporter.go
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/populate_job.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/rest.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/deployment.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/k8s_role.go
  internal/controller/reconciler/k8s_rolebinging.go
  internal/controller/reconciler/k8s_service.go
  internal/controller/reconciler/mariadb.go
  internal/controller/reconciler/otel.go
  internal/controller/reconciler/pod_monitor.go
  internal/controller/reconciler/reconciler.go
  internal/utils/mutltistep.go
  internal/values/types.go
  internal/values/validate.go
Labels: feature

#359 NOTASK: fix bug invalid memory address or nil pointer when get role
  internal/controller/reconciler/k8s_role.go
  internal/controller/reconciler/k8s_role_test.go
Labels: bug

#361 Move Pyxis from jail to images and bind-mount it
  images/common/scripts/complement_jail.sh
  images/common/scripts/install_pyxis_plugin.sh
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/nccl_benchmark/nccl_benchmark_entrypoint.sh
  images/worker/slurmd.dockerfile
Labels: feature

#365 Enable leader election for controller manager by default
  cmd/main.go
Labels: fix

#366 Change watching ns mechanism
  cmd/main.go
  internal/controller/clustercontroller/reconcile.go
Labels: bug

#368 Bump go version for gpubench
  images/worker/slurmd.dockerfile
Labels: dependencies

#369 MSP-4080: add simple rebooter
  cmd/rebooter/main.go
  internal/controller/clustercontroller/reconcile.go
  internal/controllerconfig/options.go
  internal/rebooter/reconcile.go
Labels: feature

#375 Delete unused code from checkcontroller
  internal/checkcontroller/reconcile.go
  internal/checkcontroller/reconcile_test.go
Labels: ignore-for-release

#377 MSP-4080: add rebooting node check
  go.mod
  go.sum
  internal/rebooter/reconcile.go
  internal/rebooter/reconcile_test.go
Labels: feature
