Repository nebius/soperator, pull requests merged in 2025-02, with the labels that each got.

#383 MSP-4080: add handleNodeReboot, handleNodeDrain, handleNodeUnDrain and fix patch condition
  internal/consts/conditions.go
  internal/rebooter/reconcile.go
  internal/rebooter/reconcile_test.go
Labels: feature

#387 Preinstall Nvidia mock packages issues/384
  images/jail/jail.dockerfile
  images/jail/pin_packages/cuda-pins
  images/jail/skel/.profile
Labels: feature

#390 Install nvtop as deb package from repo and bind mount it from container to the jail filesystem
  images/common/scripts/complement_jail.sh
  images/common/scripts/install_nvtop.sh
  images/jail/jail.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#394 Preinstall dcgmi tools to the jail
  images/jail/jail.dockerfile
Labels: feature

#391 MSP-4080: add render, reconcile rebooter and rbac
  Makefile
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  cmd/rebooter/main.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/rbac/clustercontroller/role.yaml
  config/rbac/node-configurator/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/soperator-helm/kustomization.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/templates/binding-rbac.yaml
  helm/soperator/templates/node-configurator-rbac.yaml
  helm/soperator/templates/serviceaccount.yaml
  internal/consts/component.go
  internal/consts/container.go
  internal/consts/label.go
  internal/consts/rebooter.go
  internal/consts/service.go
  internal/controller/clustercontroller/worker.go
  internal/naming/naming.go
  internal/rebooter/reconcile.go
  internal/rebooter/reconcile_test.go
  internal/render/worker/container.go
  internal/render/worker/daemonset.go
  internal/values/slurm_worker.go
Labels: feature

#397 Remove Nvidia CUDA from worker image and apt clean
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/install_container_toolkit.sh
  images/common/scripts/install_docker.sh
  images/common/scripts/install_docker_cli.sh
  images/common/scripts/install_enroot.sh
  images/common/scripts/install_munge.sh
  images/common/scripts/install_openmpi.sh
  images/common/scripts/install_parallel.sh
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/restd/slurmrestd.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#410 kubebuilder create api --group slurm --version v1alpha1 --kind NodeConfigurator #404
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/nodeconfigurator_types.go
  cmd/main.go
  config/crd/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/nodeconfigurator_admin_role.yaml
  config/rbac/nodeconfigurator_editor_role.yaml
  config/rbac/nodeconfigurator_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/slurm_v1alpha1_nodeconfigurator.yaml
  internal/controller/nodeconfigurator_controller.go
  internal/controller/suite_test.go
Labels: ignore-for-release

#412 hotfix: set antiaffinity if reboot enabled
  internal/render/worker/daemonset.go
Labels: ignore-for-release

#415 Build jail image based on own CUDA packages installation
  images/jail/jail.dockerfile
Labels: feature

#417 Temporary remove `expose_enroot_logs` flag
  internal/render/common/configmap.go
Labels: bug

#419 Fix ci for external contributors
  .github/workflows/one_job.yml
Labels: bug

#411 Add Epilog and Prolog options
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: feature

#418 Fix non-zero error handling in gpu_healthcheck.sh
  images/worker/scripts/gpu_healthcheck.sh
Labels: fix

#420 delete unsued watch ns
  internal/controller/clustercontroller/watch_namespaces.go
Labels: ignore-for-release

#389 Pre-create enroot credentials, exclude enroot bind-mounts from motd, make Docker mount /dev/infiniband, store /tmp on disk and add tmpfs /mnt/memory
  VERSION
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/crd/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster-storage/templates/jail-pvc.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/Chart.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/values.yaml
  images/common/nvidia-container-runtime/config.toml
  images/common/scripts/complement_jail.sh
  images/common/scripts/install_enroot.sh
  images/common/scripts/install_openmpi.sh
  images/jail/jail.dockerfile
  images/jail/motd/10-system-info
  images/jail/skel/.config/enroot/.credentials
  images/jail/skel/.profile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail_entrypoint.sh
  images/worker/slurmd.dockerfile
  internal/consts/configmap.go
  internal/consts/version.go
  internal/consts/volume.go
  internal/controller/clustercontroller/populate_job.go
  internal/render/common/configmap.go
  internal/render/common/volume.go
  internal/render/login/container.go
  internal/render/login/statefulset.go
  internal/render/login/volume.go
  internal/render/worker/container.go
  internal/render/worker/statefulset.go
  internal/render/worker/volume.go
  internal/values/slurm_cluster.go
Labels: feature, fix

#425 Move slurm packages outside the jail
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/bind_slurm_common.sh
  images/common/scripts/complement_jail.sh
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/restd/slurmrestd.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#429 add controller and CRD for node-configurator #404
  Makefile
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/extra_types.go
  api/v1alpha1/nodeconfigurator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  config/rbac/clustercontroller/role.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperator/templates/manager-rbac.yaml
  internal/consts/node_configurator.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/worker.go
  internal/controller/nodeconfigurator/nodeconfigurator_controller.go
  internal/controller/nodeconfigurator_controller.go
  internal/logfield/fields.go
  internal/naming/naming.go
  internal/render/nodeconfigurator/container.go
  internal/render/nodeconfigurator/daemonset.go
  internal/render/nodeconfigurator/pod.go
  internal/render/worker/container.go
  internal/render/worker/daemonset.go
  internal/values/slurm_worker.go
Labels: feature

#452 398: Add k8s nodes controller
  internal/checkcontroller/k8s_nodes_controller.go
  internal/checkcontroller/reconcile.go
  internal/checkcontroller/slurm_workers_controller.go
  internal/consts/conditions.go
Labels: feature

#457 Hotfix populate jail job reconciliation
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  internal/consts/version.go
  internal/controller/clustercontroller/populate_job.go
Labels: bug

#466 456: add nodeconfigurator helm charts
  Makefile
  config/nodeconfigurator/kustomization.yaml
  helm/nodeconfigurator/.helmignore
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/templates/_helpers.tpl
  helm/nodeconfigurator/templates/nodeconfigurator-cr.yaml
  helm/nodeconfigurator/values.yaml
Labels: ignore-for-release

#468 456: add cel validation nodeConfigurator
  api/v1alpha1/nodeconfigurator_types.go
  config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: feature

#475 Separate package installation and remove unused packages from conyainers
  images/accounting/slurmdbd.dockerfile
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/restd/slurmrestd.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#477 NOTIC Fix mistake in license
  LICENSE
Labels: documentation

#482 Use Nebius container mirrored images because of docker hub limits
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/templates/accounting-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/controller-spool-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-mount-daemonset.yaml
  helm/slurm-cluster-storage/templates/jail-submounts-mount-daemonset.yaml
  images/accounting/slurmdbd.dockerfile
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/munge/munge.dockerfile
  images/nccl_benchmark/nccl_benchmark.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/restd/slurmrestd.dockerfile
  images/worker/slurmd.dockerfile
  internal/render/nodeconfigurator/container.go
  internal/values/slurm_worker.go
Labels: feature

#483 fix bug rebooter with operator exist
  internal/rebooter/reconcile.go
  internal/rebooter/reconcile_test.go
Labels: ignore-for-release

#501 #485 fix bug with Replication mariadb.spec
  internal/render/accounting/mariadb.go
Labels: bug

#496 480: do not run nccl test if some proccess running on gpus
  .github/workflows/gpubench_only.yml
  images/worker/gpubench/go.mod
  images/worker/gpubench/main.go
  images/worker/gpubench/main_test.go
Labels: feature

#498 Support customisable container mounts
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/common/volume.go
  internal/render/controller/container.go
  internal/render/controller/statefulset.go
  internal/render/controller/volume.go
  internal/render/login/container.go
  internal/render/login/statefulset.go
  internal/render/login/volume.go
  internal/render/worker/container.go
  internal/render/worker/container_test.go
  internal/render/worker/statefulset.go
  internal/render/worker/volume.go
  internal/values/slurm_controller.go
  internal/values/slurm_login.go
  internal/values/slurm_worker.go
Labels: feature
