Repository nebius/soperator, pull requests merged in 2025-06, with the labels that each got.

#961 fix allocation retry error
  test/e2e/e2e_test.go
Labels: ignore-for-release

#963 add rbac list node to soperator nodetopology #427
  Makefile
  config/rbac/clustercontroller/role.yaml
  helm/soperator/templates/manager-rbac.yaml
  internal/controller/topologyconfcontroller/nodetopology_controller.go
Labels: fix

#1002 Migrate from pkg/errors to standard library and enable depguard linter
  .golangci.yaml
  go.mod
  internal/controller/clustercontroller/accounting.go
  internal/controller/clustercontroller/benchmark.go
  internal/controller/clustercontroller/common.go
  internal/controller/clustercontroller/controller.go
  internal/controller/clustercontroller/exporter.go
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/populate_job.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/rest.go
  internal/controller/clustercontroller/sconfigcontroller.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/apparmorprofile.go
  internal/controller/reconciler/deployment.go
  internal/controller/reconciler/grant.go
  internal/controller/reconciler/k8s_configmap.go
  internal/controller/reconciler/k8s_cronjob.go
  internal/controller/reconciler/k8s_daemonset.go
  internal/controller/reconciler/k8s_job.go
  internal/controller/reconciler/k8s_role.go
  internal/controller/reconciler/k8s_rolebinging.go
  internal/controller/reconciler/k8s_secret.go
  internal/controller/reconciler/k8s_service.go
  internal/controller/reconciler/k8s_service_account.go
  internal/controller/reconciler/k8s_statefulset.go
  internal/controller/reconciler/k8s_statefulset_advanced.go
  internal/controller/reconciler/mariadb.go
  internal/controller/reconciler/otel.go
  internal/controller/reconciler/pod_monitor.go
  internal/controller/reconciler/reconciler.go
  internal/controller/reconciler/versioning.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/controller/soperatorchecks/serviceaccount_controller.go
  internal/jwt/token.go
  internal/utils/multistep_test.go
  internal/utils/mutltistep.go
  internal/values/slurm_cluster.go
Labels: enhancement, go

#1005 perf: optimize build performance by removing all caching
  .github/workflows/one_job.yml
Labels: ignore-for-release

#1003 Use soperator exporter by default.
  .github/workflows/one_job.yml
  Makefile
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/values.yaml
Labels: feature

#1038 remove caching from e2e
  .github/workflows/e2e_test.yml
Labels: ignore-for-release

#1030 Change default slurm config values
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/common/configmap.go
Labels: feature

#1046 change e2e schedule to every 2 hours
  .github/workflows/e2e_test.yml
Labels: ignore-for-release

#1053 Add controller RPC metrics export
  internal/exporter/collector.go
  internal/exporter/collector_test.go
  internal/slurmapi/client.go
  internal/slurmapi/fake/mock_client.go
  internal/slurmapi/interface.go
Labels: feature

#1059 [soperator] add option supporing TopologyPlugin=topology/tree #1048
  cmd/main.go
  helm/soperator/values.yaml
Labels: feature

#1047 #1044 Add all_reduce_perf nccl check
  helm/soperator-activechecks/overrides/all_reduce_perf_nccl.yaml
  helm/soperator-activechecks/overrides/clear_enroot.yaml
  images/slurm_check_job/slurm_check_job_entrypoint.sh
  images/slurm_check_job/slurm_submit_array_job.sh
  internal/consts/slurm.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/controller/soperatorchecks/activecheck_prolog_controller.go
  internal/render/soperatorchecks/container.go
Labels: feature

#1065 add mockery to the make file
  Makefile
Labels: feature

#832 NCCL Debug SPANK plugin
  .editorconfig
  images/common/spank-nccl-debug/.clang-format
  images/common/spank-nccl-debug/.gitignore
  images/common/spank-nccl-debug/CMakeLists.txt
  images/common/spank-nccl-debug/Makefile
  images/common/spank-nccl-debug/README.md
  images/common/spank-nccl-debug/build/.gitignore
  images/common/spank-nccl-debug/docker/base.dockerfile
  images/common/spank-nccl-debug/docker/builder.dockerfile
  images/common/spank-nccl-debug/docker/headers.dockerfile
  images/common/spank-nccl-debug/src/snccld.c
  images/common/spank-nccl-debug/src/snccld.h
  images/common/spank-nccl-debug/src/snccld_args.h
  images/common/spank-nccl-debug/src/snccld_enroot.h
  images/common/spank-nccl-debug/src/snccld_log.h
  images/common/spank-nccl-debug/src/snccld_nccl.h
  images/common/spank-nccl-debug/src/snccld_state.c
  images/common/spank-nccl-debug/src/snccld_state.h
  images/common/spank-nccl-debug/src/snccld_util_dir_file.c
  images/common/spank-nccl-debug/src/snccld_util_dir_file.h
  images/common/spank-nccl-debug/src/snccld_util_host.c
  images/common/spank-nccl-debug/src/snccld_util_host.h
  images/common/spank-nccl-debug/src/snccld_util_oplock.c
  images/common/spank-nccl-debug/src/snccld_util_oplock.h
  images/common/spank-nccl-debug/src/snccld_util_string.c
  images/common/spank-nccl-debug/src/snccld_util_string.h
  images/common/spank-nccl-debug/vendor/.gitignore
Labels: feature

#1064 Implement centralized logging scheme for OpenTelemetry collector
  docs/features.md
  helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml
Labels: feature

#1066 [EPIC] Replace K8s nodes by setting conditions #913
  cmd/soperatorchecks/main.go
  helm/soperatorchecks/values.yaml
  internal/check/maintenance.go
  internal/consts/conditions.go
  internal/consts/slurm.go
  internal/controller/soperatorchecks/k8s_nodes_controller.go
  internal/controller/soperatorchecks/slurm_nodes_controller.go
  internal/controller/soperatorchecks/slurm_nodes_controller_test.go
  internal/slurmapi/node.go
Labels: feature

#1071 NOTASK: fix reread tsa token
  helm/soperator-fluxcd/templates/vm-stack.yaml
Labels: ignore-for-release

#1037 add config map with all slurm scripts (prolog, epilog, hc program, etc.)
  fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/kustomization.yaml
  helm/slurm-cluster/slurm_scripts/cleanup_enroot.sh
  helm/slurm-cluster/slurm_scripts/epilog.sh
  helm/slurm-cluster/slurm_scripts/hc_program.sh
  helm/slurm-cluster/slurm_scripts/health_checker.sh
  helm/slurm-cluster/slurm_scripts/map_job_dcgm.sh
  helm/slurm-cluster/slurm_scripts/prolog.sh
  helm/slurm-cluster/slurm_scripts/unmap_job_dcgm.sh
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/templates/slurm-scripts-cm.yaml
  helm/slurm-cluster/values.yaml
  images/worker/scripts/gpu_healthcheck.sh
  images/worker/slurmd.dockerfile
  internal/render/common/configmap.go
Labels: feature

#1077 hotfix: vmlogs render
  helm/soperator-fluxcd/templates/vm-logs.yaml
Labels: ignore-for-release

#1079 Remove validation for TaskPluginParam
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: fix

#1072 Bump release version to the 1.21.0
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1086 speedup e2e tests
  .github/workflows/e2e_test.yml
  test/e2e/e2e_test.go
Labels: ignore-for-release

#1088 hotfix: TopologyLabelPrefix name
  internal/consts/label.go
Labels: ignore-for-release

#1092 add b200 support in health checker
  helm/slurm-cluster/slurm_scripts/health_checker.sh
  helm/soperator-activechecks/overrides/all_reduce_perf_nccl.yaml
Labels: feature

#1098 hotfix: add pollInterval to otel logs jail
  helm/soperator-fluxcd/templates/opentelemetry-collector-jail-logs.yaml
  helm/soperator-fluxcd/values.yaml
Labels: fix

#1102 add region to o11y
  helm/soperator-fluxcd/templates/vm-stack.yaml
  helm/soperator-fluxcd/values.yaml
Labels: fix
