Repository nebius/soperator, pull requests merged in 2025-08, with the labels that each got.

#1352 Bump slurm 24.11.6
  Makefile
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/values.yaml
  images/accounting/slurmdbd.dockerfile
  images/common/scripts/install_container_toolkit.sh
  images/common/spank-nccl-debug/Makefile
  images/controller/slurmctld.dockerfile
  images/exporter/exporter.dockerfile
  images/jail/jail.dockerfile
  images/login/sshd.dockerfile
  images/restd/slurmrestd.dockerfile
  images/slurm_check_job/slurm_check_job.dockerfile
  images/worker/slurmd.dockerfile
Labels: feature

#1359 change e2e default terraform branch
  .github/workflows/e2e_test.yml
Labels: ignore-for-release

#1357 Release flow documentation and issue template
  .github/ISSUE_TEMPLATE/release.md
  README.md
  docs/release-flow.md
  docs/releases.md
Labels: ignore-for-release

#1362 Fix E2E test scheduler workflow gh CLI error
  .github/workflows/e2e_test_scheduler.yml
Labels: ignore-for-release

#1278 Speedup populate_jail + don't overwrite existing data
  images/common/scripts/install_awscli.sh
  images/jail/jail.dockerfile
  images/populate_jail/populate_jail.dockerfile
  images/populate_jail/populate_jail_entrypoint.sh
Labels: feature

#1363 Cancel old builds when pull request is updated
  .github/workflows/one_job.yml
Labels: ignore-for-release

#1365 Fix E2E test scheduler workflow failure for hours 08 and 09
  .github/workflows/e2e_test_scheduler.yml
Labels: ignore-for-release

#1367 fix cache-sync-timeout to k8s default
  cmd/main.go
  cmd/rebooter/main.go
  cmd/sconfigcontroller/main.go
  cmd/soperatorchecks/main.go
Labels: fix

#1375 add gpu-fryer check
  helm/soperator-activechecks/scripts/gpu-fryer.sh
  helm/soperator-activechecks/templates/gpu-fryer.yaml
  helm/soperator-activechecks/values.yaml
Labels: feature

#1368 Add memory latency and bandwidth Active Checks
  helm/soperator-activechecks/scripts/mem-bw.sh
  helm/soperator-activechecks/scripts/mem-lat.sh
  helm/soperator-activechecks/templates/mem-bw.yaml
  helm/soperator-activechecks/templates/mem-lat.yaml
  helm/soperator-activechecks/values.yaml
Labels: feature

#1382 Add self-monitoring metrics on separate port 8081
  cmd/exporter/main.go
  docs/slurm-exporter.md
  internal/consts/container.go
  internal/exporter/collector.go
  internal/exporter/collector_test.go
  internal/exporter/exporter.go
  internal/exporter/monitoring.go
  internal/exporter/monitoring_test.go
  internal/render/exporter/container.go
  internal/render/exporter/pod_monitor.go
  internal/render/exporter/pod_monitor_test.go
Labels: feature, observability

#1381 add cuda-samples test
  helm/soperator-activechecks/scripts/cuda-samples.sh
  helm/soperator-activechecks/templates/cuda-samples.yaml
Labels: feature

#1383 [nodeTopology] re-generate CM node topology if cm deleted.
  cmd/sconfigcontroller/main.go
  internal/controller/topologyconfcontroller/base_reconciler.go
  internal/controller/topologyconfcontroller/nodetopology_controller.go
  internal/controller/topologyconfcontroller/workertopology_controller.go
Labels: fix

#1391 [slurmcluster] maxUnavalaible for workes and support pre install images
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/worker/statefulset.go
  internal/values/slurm_worker.go
Labels: feature

#1394 SLURM exporter: use env configuration and improve docs
  cmd/exporter/main.go
  docs/slurm-exporter.md
  internal/render/exporter/container.go
  internal/render/exporter/container_test.go
Labels: documentation, fix

#1399 [CD] Deploy Soperator Notifier with Flux
  Makefile
  helm/soperator-fluxcd/templates/notifier.yaml
  helm/soperator-fluxcd/tests/component_enabled_test.yaml
  helm/soperator-fluxcd/tests/notifier_test.yaml
  helm/soperator-fluxcd/values.yaml
Labels: helm, ignore-for-release, observability

#1403 [CD] Support for VMAgent external labels
  helm/soperator-fluxcd/templates/vm-stack.yaml
  helm/soperator-fluxcd/tests/vmagent_test.yaml
  helm/soperator-fluxcd/values.yaml
Labels: enhancement, feature, helm, observability

#1405 fix active checks chart and image
  helm/soperator-activechecks/scripts/create-user.sh
  helm/soperator-activechecks/templates/mem-bw.yaml
  helm/soperator-activechecks/templates/mem-lat.yaml
  images/slurm_check_job/slurm_submit_array_job.sh
Labels: ignore-for-release

#1392 Undrain nodes after user problems + rewrite passive checks on Python
  helm/slurm-cluster/slurm_scripts/alloc_gpus_busy.drain.sh
  helm/slurm-cluster/slurm_scripts/alloc_gpus_busy.sh
  helm/slurm-cluster/slurm_scripts/alloc_gpus_busy.undrain.sh
  helm/slurm-cluster/slurm_scripts/alloc_mem_used.drain.sh
  helm/slurm-cluster/slurm_scripts/alloc_mem_used.undrain.sh
  helm/slurm-cluster/slurm_scripts/boot_disk_full.sh
  helm/slurm-cluster/slurm_scripts/check_runner.py
  helm/slurm-cluster/slurm_scripts/checks.json
  helm/slurm-cluster/slurm_scripts/cleanup_enroot.sh
  helm/slurm-cluster/slurm_scripts/epilog.sh
  helm/slurm-cluster/slurm_scripts/hc_program.sh
  helm/slurm-cluster/slurm_scripts/health_checker.sh
  helm/slurm-cluster/slurm_scripts/map_job_dcgm.sh
  helm/slurm-cluster/slurm_scripts/prolog.sh
  helm/slurm-cluster/slurm_scripts/unmap_job_dcgm.sh
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  images/common/scripts/reboot.sh
  images/jail/jail.dockerfile
  images/jail/motd/10-system-info
  images/jail/scripts/fs_usage.sh
  images/slurm_check_job/slurm_submit_array_job.sh
  images/worker/slurmd.dockerfile
  images/worker/supervisord_entrypoint.sh
  internal/consts/slurm.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/controller/soperatorchecks/slurm_nodes_controller.go
  internal/render/common/configmap.go
Labels: feature

#1411 fix priorityclass name for controller
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/controller/daemonset.go
  internal/render/controller/daemonset_test.go
  internal/render/controller/statefulset.go
  internal/render/controller/statefulset_test.go
  internal/values/slurm_controller.go
Labels: fix

#1413 change helmReleaseTriggerOperator
  helm/soperator-fluxcd/templates/helmrelease-trigger-operator.yaml
  helm/soperator-fluxcd/values.yaml
Labels: ignore-for-release

#1416 bump k8s to 0.33.3 and controller-runtime to 0.21.0
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
  config/crd/bases/slurm.nebius.ai_nodesets.yaml
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  go.mod
  go.sum
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: ignore-for-release

#1420 fix issue with metadata.resourceVersion: Invalid value: 0x0: must be specified for an Patch in ASTS
  internal/controller/reconciler/k8s_statefulset.go
  internal/controller/reconciler/reconciler.go
Labels: bug, fix

#1425 DCGM exporter Helm chart: support metricRelablings
  .github/workflows/pr_labels.yml
  helm/soperator-dcgm-exporter/templates/servicemonitor.yaml
  helm/soperator-dcgm-exporter/values.yaml
Labels: helm

#1415 Standalone Slurm exporter - No Kubernetes needed
  cmd/exporter/main.go
  internal/slurmapi/client.go
Labels: feature

#1423 Pre release fixes 1.22/0
  helm/slurm-cluster/slurm_scripts/alloc_gpus_busy.drain.sh
  helm/slurm-cluster/slurm_scripts/alloc_gpus_busy.undrain.sh
  helm/slurm-cluster/slurm_scripts/alloc_mem_used.drain.sh
  helm/slurm-cluster/slurm_scripts/alloc_mem_used.undrain.sh
  helm/slurm-cluster/slurm_scripts/boot_disk_full.sh
  helm/slurm-cluster/slurm_scripts/cleanup_enroot.sh
  helm/slurm-cluster/slurm_scripts/epilog.sh
  helm/slurm-cluster/slurm_scripts/free_shmem.sh
  helm/slurm-cluster/slurm_scripts/hc_host_service.sh
  helm/slurm-cluster/slurm_scripts/hc_ib_counters.sh
  helm/slurm-cluster/slurm_scripts/hc_ib_link_state.sh
  helm/slurm-cluster/slurm_scripts/hc_ib_pkey.sh
  helm/slurm-cluster/slurm_scripts/hc_program.sh
  helm/slurm-cluster/slurm_scripts/hc_xid.sh
  helm/slurm-cluster/slurm_scripts/health_checker.sh
  helm/slurm-cluster/slurm_scripts/map_job_dcgm.sh
  helm/slurm-cluster/slurm_scripts/prolog.sh
  helm/slurm-cluster/slurm_scripts/unmap_job_dcgm.sh
  helm/slurm-cluster/templates/slurm-scripts-cm.yaml
  helm/soperator-activechecks/values.yaml
  images/jail/jail.dockerfile
  images/jail/scripts/createuser.py
  images/jail/scripts/createuser.sh
  images/jail/skel/.ssh/config
  images/worker/slurmd.dockerfile
Labels: fix

#1433 Fix pagination issue in cache
  cmd/main.go
  internal/controller/topologyconfcontroller/nodetopology_controller.go
  internal/controller/topologyconfcontroller/nodetopology_controller_test.go
Labels: fix

#1434 [SlurmCluster CRD] rewrite logic of printcolumn
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/sconfigcontroller.go
  internal/controller/clustercontroller/worker.go
Labels: feature

#1429 fix observability projects
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/base/soperator-fluxcd/resources.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-events.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-jail-logs.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml
  helm/soperator-fluxcd/templates/vm-stack.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: fix

#1431 Clean old logs from /opt/soperator-outputs
  helm/soperator-activechecks/scripts/create-user.sh
  helm/soperator-activechecks/scripts/install-package.sh
  helm/soperator-activechecks/scripts/soperator-outputs-logs-cleaner.sh
  helm/soperator-activechecks/scripts/ssh-check.sh
  helm/soperator-activechecks/scripts/upgrade-cuda.sh
  helm/soperator-activechecks/scripts/upgrade-health-checker.sh
  helm/soperator-activechecks/templates/soperator-outputs-logs-cleaner.yaml
  images/k8s_check_job/k8s_check_job.dockerfile
Labels: feature

#1437 Cherry pick soperator 1.21.10
  VERSION
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/soperatorchecks/kustomization.yaml
  fluxcd/environment/nebius-cloud/dev/bootstrap/flux-kustomization.yaml
  fluxcd/environment/nebius-cloud/prod/bootstrap/flux-kustomization.yaml
  helm/nodeconfigurator/Chart.yaml
  helm/nodeconfigurator/values.yaml
  helm/slurm-cluster-storage/Chart.yaml
  helm/slurm-cluster/Chart.yaml
  helm/slurm-cluster/values.yaml
  helm/soperator-activechecks/Chart.yaml
  helm/soperator-activechecks/values.yaml
  helm/soperator-crds/Chart.yaml
  helm/soperator-dcgm-exporter/Chart.yaml
  helm/soperator-fluxcd/Chart.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-events.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-jail-logs.yaml
  helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml
  helm/soperator-fluxcd/templates/vm-stack.yaml
  helm/soperator-fluxcd/tests/vmagent_test.yaml
  helm/soperator-fluxcd/values.yaml
  helm/soperator-notifier/Chart.yaml
  helm/soperator/Chart.yaml
  helm/soperator/values.yaml
  helm/soperatorchecks/Chart.yaml
  helm/soperatorchecks/values.yaml
  internal/consts/version.go
Labels: ignore-for-release

#1440 cleanup configmap with old ib checks
  helm/slurm-cluster/templates/slurm-scripts-cm.yaml
Labels: ignore-for-release

#1442 Disable acctg by default
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: fix

#1450 Fix error with read-only workdir in dcgmi_diag_r1 health-checker
  helm/slurm-cluster/slurm_scripts/gpu_health_check.py
Labels: fix

#1455 [sconfigcontroller] fix reconcile jailedconfig
  api/v1alpha1/jailedconfig_types.go
  cmd/sconfigcontroller/main.go
  config/crd/bases/slurm.nebius.ai_jailedconfigs.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/consts/field.go
  internal/consts/label.go
  internal/controller/sconfigcontroller/jailedconfig_controller.go
  internal/controller/sconfigcontroller/jailedconfig_controller_test.go
  internal/controller/topologyconfcontroller/workertopology_controller.go
Labels: bug

#1463 [sconfigcontroller]: linux fallback to os.Rename with logs when rename unsupported; add log on exchange failure in batch (#1452)
  internal/controller/sconfigcontroller/fs_linux.go
Labels: bug

#1472 Fix building images across platforms
  .github/workflows/one_job.yml
Labels: feature

#1473 rewrote msg for pod ephemeral storage
  internal/controller/soperatorchecks/pod_ephemeral_storage_check.go
Labels: ignore-for-release

#1474 fix getting error when [user_problem] reason #1468
  .github/workflows/one_job.yml
  internal/controller/soperatorchecks/slurm_nodes_controller.go
Labels: fix

#1483 [Fix] Add +x to auto-merge-back.sh
  .github/workflows/scripts/auto-merge-back.sh
Labels: ignore-for-release

#1480 Handle boolean defaults to true in Slurm Cluster CRDs
  api/v1/slurmcluster_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/activecheck_types.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/render/common/configmap.go
  internal/render/common/configmap_test.go
  internal/values/slurm_exporter.go
Labels: ignore-for-release

#1482 `hostUsers` must be false to use `Unmasked`
  internal/render/accounting/pod.go
  internal/render/controller/daemonset.go
  internal/render/controller/statefulset.go
  internal/render/exporter/pod.go
  internal/render/login/statefulset.go
  internal/render/nodeconfigurator/pod.go
  internal/render/populate_jail/job.go
  internal/render/prometheus/pod.go
  internal/render/rest/pod.go
  internal/render/sconfigcontroller/pod.go
  internal/render/soperatorchecks/pod.go
  internal/render/worker/statefulset.go
Labels: fix

#1494 fix doc Soperator Helm chart
  helm/soperator/README.md
Labels: documentation

#1466 NFS server Helm chart
  Makefile
  helm/nfs-server/.helmignore
  helm/nfs-server/Chart.yaml
  helm/nfs-server/README.md
  helm/nfs-server/templates/_helpers.tpl
  helm/nfs-server/templates/configmap.yaml
  helm/nfs-server/templates/priorityclass.yaml
  helm/nfs-server/templates/service.yaml
  helm/nfs-server/templates/serviceaccount.yaml
  helm/nfs-server/templates/servicemonitor.yaml
  helm/nfs-server/templates/statefulset.yaml
  helm/nfs-server/templates/storageclass.yaml
  helm/nfs-server/templates/tests/test-configmap-exports.yaml
  helm/nfs-server/templates/tests/test-nfs-connectivity.yaml
  helm/nfs-server/values.yaml
Labels: helm

#1497 add activechecks PrinterColumns
  api/v1alpha1/activecheck_types.go
  api/v1alpha1/jailedconfig_types.go
  api/v1alpha1/nodeconfigurator_types.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  config/crd/bases/slurm.nebius.ai_jailedconfigs.yaml
  config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
Labels: feature

#1507 fix patch cm with empty labels
  internal/controller/reconciler/k8s_configmap.go
Labels: bug

#1519 add priorityclassname for components of clurm cluster
  api/v1/slurmcluster_types.go
  config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
  helm/slurm-cluster/templates/priority-class.yaml
  helm/slurm-cluster/templates/slurm-cluster-cr.yaml
  helm/slurm-cluster/tests/priority-class_test.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  internal/render/accounting/pod.go
  internal/render/accounting/pod_test.go
  internal/render/exporter/pod.go
  internal/render/exporter/pod_test.go
  internal/render/login/statefulset.go
  internal/render/login/statefulset_test.go
  internal/render/populate_jail/job.go
  internal/render/populate_jail/job_test.go
  internal/render/rest/pod.go
  internal/render/sconfigcontroller/pod.go
  internal/render/sconfigcontroller/pod_test.go
Labels: feature
