Repository nebius/soperator, pull requests merged in 2025-04, with the labels that each got.

#582 Soperatorchecks k8s job
  cmd/soperatorchecks/main.go
  config/rbac/soperatorchecks/role.yaml
  go.mod
  go.sum
  helm/soperatorchecks/templates/soperator-checks-rbac.yaml
  internal/consts/component.go
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/soperatorchecks.go
  internal/render/common/pod.go
  internal/render/common/pod_test.go
  internal/render/prometheus/pod.go
  internal/render/soperatorchecks/container.go
  internal/render/soperatorchecks/cronjob.go
  internal/render/soperatorchecks/pod.go
Labels: feature

#635 [fluxcd] add soperator helm chart to fluxcd #617
  fluxcd/base/nodeconfigurator/kustomization.yaml
  fluxcd/base/nodeconfigurator/resources.yaml
  fluxcd/base/soperator/kustomization.yaml
  fluxcd/base/soperator/resources.yaml
  fluxcd/base/soperatorchecks/kustomization.yaml
  fluxcd/base/soperatorchecks/resources.yaml
  fluxcd/enviroment/local/base/kustomization.yaml
  fluxcd/enviroment/nebius-cloud/base/kustomization.yaml
Labels: ignore-for-release

#634 #618: [Speedup] Disable ldconfig on nvidia driver configuration.
  images/common/scripts/complement_jail.sh
Labels: enhancement

#651 fux bug oci security-profiles-operator
  fluxcd/base/security-profiles-operator/resources.yaml
Labels: ignore-for-release

#652 Flux test
  fluxcd/base/mariadb-operator/resources.yaml
  fluxcd/base/nodeconfigurator/resources.yaml
  fluxcd/base/opentelemetry-collector-events/resources.yaml
  fluxcd/base/opentelemetry-collector-logs/resources.yaml
  fluxcd/base/security-profiles-operator/resources.yaml
  fluxcd/base/slurm-cluster-storage/resources.yaml
  fluxcd/base/slurm-cluster/resources.yaml
  fluxcd/base/soperator/resources.yaml
  fluxcd/base/soperatorchecks/resources.yaml
  fluxcd/base/victoria-logs/resources.yaml
  fluxcd/base/victoria-metrics-operator/resources.yaml
Labels: ignore-for-release

#625 [BUG] do not reconcile on heartbeat
  internal/controller/soperatorchecks/k8s_nodes_controller.go
Labels: bug

#663 Add golangilint to CI
  .github/workflows/one_job.yml
  .golangci.yaml
  Makefile
Labels: ignore-for-release

#705 [fluxcd] add crds and dependency on cds and ns #653
  fluxcd/README.md
  fluxcd/base/cert-manager/resources.yaml
  fluxcd/base/fluxcd/resources.yaml
  fluxcd/base/mariadb-operator/resources.yaml
  fluxcd/base/namespaces/resources.yaml
  fluxcd/base/nodeconfigurator/resources.yaml
  fluxcd/base/nvidia-gpu-operator/resources.yaml
  fluxcd/base/nvidia-network-operator/resources.yaml
  fluxcd/base/opentelemetry-collector-events/resources.yaml
  fluxcd/base/opentelemetry-collector/kustomization.yaml
  fluxcd/base/opentelemetry-collector/resources.yaml
  fluxcd/base/prometheus-operator-crds/kustomization.yaml
  fluxcd/base/prometheus-operator-crds/resources.yaml
  fluxcd/base/security-profiles-operator/resources.yaml
  fluxcd/base/slurm-cluster-storage/resources.yaml
  fluxcd/base/slurm-cluster/resources.yaml
  fluxcd/base/soperator/resources.yaml
  fluxcd/base/soperatorchecks/resources.yaml
  fluxcd/base/victoria-logs/resources.yaml
  fluxcd/base/victoria-metrics-operator/kube-state-metrics-config/kube-state-metrics-config.yaml
  fluxcd/base/victoria-metrics-operator/kube-state-metrics-config/kustomization.yaml
  fluxcd/base/victoria-metrics-operator/kustomization.yaml
  fluxcd/base/victoria-metrics-operator/resources.yaml
  fluxcd/enviroment/local/base/kustomization.yaml
  fluxcd/enviroment/local/soperator-kind/bootstrap/git-repository.yaml
  fluxcd/enviroment/nebius-cloud/base/kustomization.yaml
  fluxcd/enviroment/nebius-cloud/soperator-infra/bootstrap/git-repository.yaml
  fluxcd/enviroment/nebius-cloud/soperator-infra/kustomization.yaml
  fluxcd/enviroment/nebius-cloud/soperator/bootstrap/git-repository.yaml
Labels: ignore-for-release

#703 #639 Change ActiveCheck CR status based on k8s jobs
  api/v1alpha1/activecheck_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/soperatorchecks/main.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  config/rbac/soperatorchecks/role.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperatorchecks/templates/soperator-checks-binding-rbac.yaml
  helm/soperatorchecks/templates/soperator-checks-rbac.yaml
  internal/consts/annotation.go
  internal/consts/conditions.go
  internal/controller/soperatorchecks/activecheck_jobs_controller.go
  internal/controller/soperatorchecks/soperatorchecks.go
  internal/render/soperatorchecks/cronjob.go
Labels: feature

#672 #623 Advanced stateful sets
  cmd/main.go
  config/rbac/clustercontroller/role.yaml
  go.mod
  go.sum
  helm/soperator/.gitignore
  helm/soperator/Chart.yaml
  helm/soperator/README.md
  helm/soperator/charts/.gitkeep
  helm/soperator/templates/manager-rbac.yaml
  helm/soperator/values.yaml
  internal/check/consts.go
  internal/controller/clustercontroller/controller.go
  internal/controller/clustercontroller/exporter.go
  internal/controller/clustercontroller/login.go
  internal/controller/clustercontroller/reconcile.go
  internal/controller/clustercontroller/rest.go
  internal/controller/clustercontroller/worker.go
  internal/controller/reconciler/k8s_statefulset_advanced.go
  internal/controller/reconciler/reconciler.go
  internal/render/common/container.go
  internal/render/common/pod.go
  internal/render/common/probe.go
  internal/render/common/volume.go
  internal/render/controller/container.go
  internal/render/controller/statefulset.go
  internal/render/login/container.go
  internal/render/login/statefulset.go
  internal/render/login/volume.go
  internal/render/worker/container.go
  internal/render/worker/statefulset.go
  internal/render/worker/volume.go
  release_helm.sh
Labels: dependencies, go, feature, helm

#732 Rename `createuser` to `screateuser`
  images/jail/jail.dockerfile
  images/jail/scripts/screateuser.sh
Labels: enhancement, docker

#733 add manual job trigger for runAfterCreation
  api/v1alpha1/activecheck_types.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  config/rbac/soperatorchecks/role.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  helm/soperatorchecks/templates/soperator-checks-rbac.yaml
  internal/controller/soperatorchecks/activecheck_controller.go
  internal/controller/soperatorchecks/soperatorchecks.go
  internal/render/soperatorchecks/job.go
Labels: feature

#748 add e2e schedule
  .github/workflows/e2e_test.yml
Labels: github_actions

#756 reduce logs in e2e
  .github/workflows/e2e_test.yml
  test/e2e/e2e_test.go
Labels: github_actions, test

#743 #707 [soperatorchecks] Create slurmJob check type
  api/v1alpha1/activecheck_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/slurm.nebius.ai_activechecks.yaml
  helm/soperator-crds/templates/slurmcluster-crd.yaml
  helm/soperator/crds/slurmcluster-crd.yaml
  images/munge/munge.dockerfile
  images/munge/munge_entrypoint.sh
  internal/render/common/container.go
  internal/render/soperatorchecks/container.go
  internal/render/soperatorchecks/pod.go
Labels: feature
